import type { Metadata } from "next"
import { Geist_Mono } from "next/font/google"
import "./globals.css"
import Providers from "@/components/providers"

const jetbrainsMono = Geist_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
})
export const metadata: Metadata = {
  title: "Realtime Chat App",
  description: "Generated by Khemraj Fekar",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
